
server:
  port: 8040
spring:
  data:
    mongodb:
      username: rizwan
      password: rizwan312
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092

      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.rizwan.ecomerce.Notification.kafka.order.OrderConfirmation,paymentConfirmation:com.rizwan.ecomerce.Notification.kafka.payment.PaymentConfirmation
  mail:
    host: localhost
    port: 1025
    username: rizwan
    password: rizwan312
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000